var user_date_id = {
      maxId:12,
      folder:[
          {
              name:"云盘",
              id:0,
              pid:"root",
              time:Date.now(),
              child:[
                  {
                      name:"我的电影",
                      id:1,
                      pid:0,
                      check:false,
                      time:Date.now(),
                      child:[
                          {
                              name:"科幻电影",
                              id:9,
                              pid:1,
                              check:false,
                              time:Date.now(),
                              child:[]
                          },
                          {
                              name:"喜剧电影",
                              id:10,
                              pid:1,
                              check:false,
                              time:Date.now(),
                              child:[]
                          }
                      ]
                  },
                  {
                      name:"我的音乐",
                      id:2,
                      pid:0,
                      check:false,
                      time:Date.now(),
                      child:[
                          {
                              name:"刘德华",
                              id:3,
                              pid:2,
                              check:false,
                              time:Date.now(),
                              child:[
                                  {
                                      name:"粤语",
                                      id:7,
                                      pid:3,
                                      check:false,
                                      time:Date.now(),
                                      child:[]
                                  },
                                  {
                                      name:"国语",
                                      id:8,
                                      pid:3,
                                      check:false,
                                      time:Date.now(),
                                      child:[]
                                  }
                              ]
                          },
                          {
                              name:"汪峰",
                              id:4,
                              pid:2,
                              check:false,
                              time:Date.now(),
                              child:[]
                          },
                          {
                              name:"Beyond",
                              id:5,
                              pid:2,
                              check:false,
                              time:Date.now(),
                              child:[]
                          }
                      ]
                  },
                  {
                      name:"我的小说",
                      id:6,
                      pid:0,
                      check:false,
                      time:Date.now(),
                      child:[
                          {
                              name:"长篇小说",
                              id:11,
                              pid:6,
                              check:false,
                              time:Date.now(),
                              child:[]
                          },
                          {
                              name:"短篇小说",
                              id:12,
                              pid:6,
                              check:false,
                              time:Date.now(),
                              child:[]
                          }
                      ]
                  }
              ]
          }
      ]
};
var data = user_date_id.folder;